#!/bin/sh
if [ -z "${IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/luci-autossh ) && rm -f /etc/uci-defaults/luci-autossh
	chmod 755 /etc/init.d/autossh >/dev/null 2>&1
	/etc/init.d/autossh enable >/dev/null 2>&1
fi
exit 0
